// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Execute provides a mock function with given fields: sound
func (_m *Service) Execute(sound string) error {
	ret := _m.Called(sound)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sound)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
